image: node:20

pipelines:
  branches:
    main:
    - step:
        name: install
        caches:
          - node
        script:
          - rm -rf node_modules package-lock.json
          - npm install --legacy-peer-deps 

    - parallel:
      - step:
          name: Build
          caches:
            - node
          script:
            - rm -rf node_modules package-lock.json
            - npm install --legacy-peer-deps
            - npm run build              
            - mv web.config dist/  # Move web.config inside dist/
            - apt update && apt install zip
            - zip -r app-$BITBUCKET_BUILD_NUMBER.zip dist package.json -x *.git* bitbucket-pipelines.yml
          artifacts:
            - "*.zip"
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1            
              
    - step:
        name: Deploy to Production
        trigger: manual
        deployment: Production
        script:
          - pipe: atlassian/azure-web-apps-deploy:1.2.3
            variables:
              AZURE_APP_ID: $AZURE_APP_ID
              AZURE_PASSWORD: $AZURE_PASSWORD
              AZURE_TENANT_ID: $AZURE_TENANT_ID
              AZURE_RESOURCE_GROUP: $AZURE_RESOURCE_GROUP
              AZURE_APP_NAME: $AZURE_APP_NAME
              ZIP_FILE: 'app-$BITBUCKET_BUILD_NUMBER.zip'
              DEBUG: 'true'